server.port=8081

#------------MYSQL------------------
spring.datasource.url=jdbc:mysql://localhost:3306/rameshf_employee_ms
spring.datasource.username=root
spring.datasource.password=root
#------------MYSQL------------------

#------------Hibernate-JPA------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#------------Hibernate-JPA------------------

#------------eureka-client------------------
#spring.application.name=employee-service
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
#------------eureka-client------------------

spring.boot.message=Hello, Employee service
